- hosts: managedHosts
  gather_facts: false
  collections:
    - community.general
  tasks:
    - name: Get power state
      delegate_to: localhost
      command:
        cmd: ipmitool -I lanplus -U "{{ bmcUser }}" -P "{{ bmcPassword }}" -H "{{ bmcAddress }}" chassis power status
      register: powerState

    - name: Display power state
      debug:
        msg: "Power state: {{ powerState.stdout }}"
