- hosts: managedHosts
  gather_facts: false
  collections:
    - community.general
  vars:
    validResetTypes:
      - "On"
      - ForceOff
      - ForceRestart
      - GracefulShutdown
      - PushPowerButton
      - NMI
  tasks:
    - when: resetType|default("") not in validResetTypes
      run_once: true
      fail:
        msg: |-
          `resetType` must be set to one of {{ validResetTypes|join(", ") }}

    - name: Perform power action ({{ resetType }})
      delegate_to: localhost
      ignore_errors: true
      uri:
        url: "{{ redfishBaseURL }}{{ redfishComputerSystemResetAction }}"
        method: POST
        body_format: json
        body:
          ResetType: "{{ resetType }}"
        url_username: root
        url_password: "{{ bmcPassword }}"
        validate_certs: false
        status_code:
          - 200
          - 204
      register: power

    - name: Report errors
      when: power is failed
      block:
        - debug:
            msg: "{{ power.json }}"

        - fail:
