- hosts: managedHosts
  gather_facts: false
  collections:
    - community.general
  tasks:
    - name: Get system information
      delegate_to: localhost
      uri:
        url: "{{ redfishBaseURL }}{{ redfishSystemEndpoint }}"
        url_username: "{{ bmcUsername }}"
        url_password: "{{ bmcPassword }}"
        validate_certs: false
        force_basic_auth: true
      register: system

    - name: Display power state
      debug:
        msg: "Power state: {{ system.json.PowerState }}"
